Switched to new-style classes, because Django database lookups filtering on Money objects would cause "AttributeError: class Money has no attribute '__mro__'" on Python 2.6. Not sure if this is the best way to fix it, but it appears to work